version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    container_name: 'redis-weather'
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass jshdf43t67_ywdh+g432i7fywhefugvytf&*
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local